services:
    Integrations\GrumPhpDoctrineTask\DoctrineSchemaValidateTask:
        class: Integrations\GrumPhpDoctrineTask\DoctrineSchemaValidateTask
        arguments:
            - "@process_builder"
            - "@formatter.raw_process"
        tags:
            - { name: grumphp.task, task: doctrine_schema_validate }
